export const items = [
  {
    id: 1,
    name: "1-mavzu",
    url: "https://www.youtube.com/watch?v=f58AL6ThPnI",
    content: "content - 1",
    panel: "panel1",
  },
  {
    id: 2,
    name: "2-mavzu",
    url: "https://youtu.be/-VKvMlgutJs",
    content: "content - 2",
    panel: "panel2",
  },
  {
    id: 3,
    name: "3-mavzu",
    url: "https://youtu.be/jwHiG1-CEP4",
    content: "content - 3",
    panel: "panel3",
  },
  {
    id: 4,
    name: "4-mavzu",
    url: "https://youtu.be/gIaPTxpVIg0",
    content: "content - 4",
    panel: "panel4",
  },
  {
    id: 5,
    name: "5-mavzu",
    url: "https://youtu.be/8dA-4XK06lU",
    content: "content - 5",
    panel: "panel5",
  },
  {
    id: 6,
    name: "6-mavzu",
    url: "https://youtu.be/Q3hJQc3sN-E",
    content: "content - 6",
    panel: "panel6",
  },
  {
    id: 7,
    name: "7-mavzu",
    url: "https://youtu.be/f5OOXkrJdmk",
    content: "content - 7",
    panel: "panel7",
  },
  {
    id: 8,
    name: "8-mavzu",
    url: "https://youtu.be/RPyCNd50qdw",
    content: "content - 8",
    panel: "panel8",
  },
  {
    id: 9,
    name: "9-mavzu",
    url: "https://youtu.be/FJSvTjmsNMA",
    content: "content - 9",
    panel: "panel9",
  },
  {
    id: 10,
    name: "10-mavzu",
    url: "https://youtu.be/jlwgqInXGgg",
    content: "content - 10",
    panel: "panel10",
  },
  {
    id: 11,
    name: "11-mavzu",
    url: "https://youtu.be/HyJb2mekI1I",
    content: "content - 11",
    panel: "panel11",
  },
];
